[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.3"
lazy_static = "1.4.0"
log = "0.4.21"
rand = "0.8.5"
structopt = "0.3.26"
